apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-ip-discovery
  namespace: pvtlnpoc2
  labels:
    app: pod-ip-discovery
spec:
  selector:
    matchLabels:
      name: pod-ip-discovery
  template:
    metadata:
      labels:
        name: pod-ip-discovery
    spec:
      containers:
      - name: pod-ip-discovery
        image: tanfarming/pvtln-discov:v1
        env:
          - name: imdgNamespace
            value: "pvtlnpoc2"
          - name: imdgPodSelector
            value: "role=hazelcast"
          - name: zonalNameMap
            value: >-
              {
                "us-east-2a":"vpce-0a842fed617cc9301-2x9w4vz7-us-east-2a.vpce-svc-07563c56b56202afc.us-east-2.vpce.amazonaws.com",
                "us-east-2b":"vpce-0a842fed617cc9301-2x9w4vz7-us-east-2b.vpce-svc-07563c56b56202afc.us-east-2.vpce.amazonaws.com",
                "us-east-2c":"vpce-0a842fed617cc9301-2x9w4vz7-us-east-2c.vpce-svc-07563c56b56202afc.us-east-2.vpce.amazonaws.com"
              }
        imagePullPolicy: Always
        ports:
          - containerPort: 5700
            hostPort: 5700
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-list-pods-nodes
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvtlnpoc2-default-view-pods-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-list-pods-nodes
subjects:
- kind: ServiceAccount
  name: default
  namespace: pvtlnpoc2      